# Generated by Django 2.1.7 on 2019-09-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=55, verbose_name='✒️ Nombres')),
                ('lastname', models.CharField(max_length=55, verbose_name='✒️ Apellidos')),
                ('phone', models.BigIntegerField(verbose_name=' 📱 Telefono')),
                ('email', models.EmailField(max_length=254, verbose_name='📫 Correo electronico')),
                ('infromation', models.TextField(blank=True, max_length=500, null=True, verbose_name='💬 Informacion adicional')),
            ],
        ),
    ]
